Currency.create!(iso_code: 'USD', name: 'US dollars',        format: '$%{amount}', decimal_digits: 2) 
Currency.create!(iso_code: 'EUR', name: 'euros',             format: '€%{amount}', decimal_digits: 2) 
Currency.create!(iso_code: 'TRY', name: 'Turkish lira',      format: '₺%{amount}', decimal_digits: 2) 
Currency.create!(iso_code: 'HUF', name: 'Hungarian forints', format: '%{amount} Ft', decimal_digits: 0) 
Currency.create!(iso_code: 'CZK', name: 'Czech koruna',      format: '%{amount} Kč', decimal_digits: 2) 
Currency.create!(iso_code: 'GBP', name: 'British pounds',    format: '£%{amount}', decimal_digits: 2) 
Currency.create!(iso_code: 'BGN', name: 'Bulgarian lev',     format: '%{amount} лв.', decimal_digits: 2) 
Currency.create!(iso_code: 'HRK', name: 'Croatian kuna',     format: '%{amount} kn', decimal_digits: 2) 
Currency.create!(iso_code: 'ILS', name: 'Israeli shekels',   format: '₪ %{amount}', decimal_digits: 2) 
Currency.create!(iso_code: 'CHF', name: 'Swiss francs',      format: '%{amount} %{iso_code}', decimal_digits: 2) 
